using System.Collections.Generic;
using UnityEngine;

namespace IronNight
{
    /// <summary>
    /// The crew's letters home. Each of the crew writes three: after their first night in the seat, at the third level
    /// of their training and at the fifth. The platoon's commander reads them before they go, as officers did, and
    /// passes them with the censor's stamp; then they are sent, and kept to be read again. The Americans write from
    /// Normandy to the Ardennes to Germany in 1944 and 1945; the Soviets from Kursk in 1943 through Belorussia to Germany.
    /// </summary>
    public static class Letters
    {
        public class Letter { public string man, place, body; public int at; }

        /// <summary>Who each of them writes to.</summary>
        public static readonly Dictionary<string, string> To = new Dictionary<string, string>
        {
            { "us_gunner_1", "Mrs. Martha Whitaker, Grundy Center, Iowa" },
            { "us_gunner_2", "Mrs. Nora Thompson, Asheville, North Carolina" },
            { "us_gunner_3", "Mr. Ramón Delgado, Tucson, Arizona" },
            { "us_gunner_4", "Mr. Patrick O'Hara, Kensington, Philadelphia" },
            { "us_loader_1", "Mrs. Guadalupe Moreno, Boyle Heights, Los Angeles" },
            { "us_loader_2", "Miss Betty Kaminski, Pittsburgh, Pennsylvania" },
            { "us_loader_3", "Mrs. Rosa Ferrante, Red Hook, Brooklyn" },
            { "us_loader_4", "Mrs. Stella Kowalski, Milwaukee, Wisconsin" },
            { "us_driver_1", "Master Stanley Kowalczyk, Back of the Yards, Chicago" },
            { "us_driver_2", "Mrs. Helen Novak, Dearborn, Michigan" },
            { "us_driver_3", "Mme. Odile Beaumont, Lafayette, Louisiana" },
            { "us_driver_4", "Miss Carmen Reyes, El Paso, Texas" },
            { "us_radio_1", "Miss Elena Garza, Guadalupe Street, San Antonio" },
            { "us_radio_2", "Mrs. Mary Whitehorse, Gallup, New Mexico" },
            { "us_radio_3", "Mrs. Kathleen Brennan, Dorchester, Boston" },
            { "us_radio_4", "Lt. David Price, Navy Air Group, Pacific Fleet" },
            { "su_gunner_1", "Maria Ivanovna Petrova, Dyadkovo, Ryazan region" },
            { "su_gunner_2", "Darya Zaytseva, near Irkutsk" },
            { "su_gunner_3", "Professor Sergei Rudnev, Moscow" },
            { "su_gunner_4", "Elena Voronova, Smolensk" },
            { "su_loader_1", "Tatyana Nikitina, the tank works, Chelyabinsk" },
            { "su_loader_2", "Anna Krylova, on the Volga, Saratov region" },
            { "su_loader_3", "Galina Gorbunova, Stalino, the Donbass" },
            { "su_loader_4", "Nina Orlova, the textile mill, Ivanovo" },
            { "su_driver_1", "Grandad Denisov, the kolkhoz, the Kuban" },
            { "su_driver_2", "Vera Sokolova, Gorky" },
            { "su_driver_3", "Olena Kolesnik, near Poltava" },
            { "su_driver_4", "Sapper Pyotr Kuznetsov, field post" },
            { "su_radio_1", "Maria Volkova, Moscow" },
            { "su_radio_2", "Klavdia Belyaeva, Gorky" },
            { "su_radio_3", "Lidia Frolova, Pskov" },
            { "su_radio_4", "Granny Petrenko, Kharkiv" },
        };

        const string France = "Somewhere in France · July 1944", Belgium = "Somewhere in Belgium · December 1944", Germany = "Somewhere in Germany · April 1945";
        const string Kursk = "Field post · near Kursk · July 1943", Belorussia = "Field post · Belorussia · June 1944", Reich = "Field post · Germany · April 1945";

        public static readonly Letter[] All =
        {
            // ---- the Americans ----
            new Letter { man = "us_gunner_1", at = 1, place = France, body = "Dear Mom,\nI'm the gunner now. Sarge says I've got the steadiest hands in the platoon, which is Dad's doing, all those mornings after pheasants. The tank is loud and hot and smells like a tractor shed, so I feel right at home. The fellows are good. Frank talks about his baby girl all day and Eddie drives like he stole the thing. Don't worry about me, and don't let June feed Duke from the table. Tell Dad the corn here looks short next to ours.\nYour son, Dale" },
            new Letter { man = "us_gunner_1", at = 3, place = Belgium, body = "Dear Mom,\nIt snowed three days straight. We sleep under the tank with the engine warm above us, so don't picture me cold. I had a birthday last week, twenty now. Frank found a candle and stuck it in a cracker, and the whole crew sang, even Sam, who can't. We've been through some hard nights and I won't say more than that, but I keep my hands steady and my head down like Dad taught me. Kiss June for me. Save me a slice of pie for next year.\nLove, Dale" },
            new Letter { man = "us_gunner_1", at = 5, place = Germany, body = "Dear Mom,\nThe fellows say it could be over by summer. I don't let myself think about it too much. I've been a gunner longer than anybody in the company now, and the new boys come to me to ask how. I tell them what Dad told me: breathe out, then squeeze. I want to be home for the planting, or the harvest if I'm late. I dream about the kitchen, the screen door, Duke on the porch. Keep the light on, Mom. I'm coming.\nYour son, Dale" },

            new Letter { man = "us_gunner_2", at = 1, place = France, body = "Dear Nora,\nThey put me on the gun because I spotted an antitank gun at eight hundred yards that nobody else could see. The lieutenant asked how, and I said squirrels are smaller. The country here is all hedges and little fields, nothing like home. No mountains. I miss the Blue Ridge more than I figured. Tell Jimmy his daddy is fine and that the tank is bigger than Uncle Ray's barn. Kiss him on the top of his head the way he hates.\nYour husband, Ike" },
            new Letter { man = "us_gunner_2", at = 3, place = Belgium, body = "Dear Nora,\nHills at last. These Ardennes put me in mind of home, the same pines, the same fog lying in the hollows of a morning. Only the fog here hides tanks, not deer. I've got good eyes, you know that, and they've kept the crew out of trouble more than once. I don't sleep much. When I do I dream about our kitchen and you humming by the stove. Jimmy's birthday is coming. Give him the pocketknife in my top drawer. He's old enough if you show him.\nIke" },
            new Letter { man = "us_gunner_2", at = 5, place = Germany, body = "Dear Nora,\nI watched the sun come up over a German river this morning and I thought, that's the same sun coming up over Mount Pisgah. It don't know about the war. We'll be done soon. I want to take Jimmy fishing on the French Broad, just the two of us, and not say a word all day. That's what I want most. Quiet, and the three of us. I'll be the one on the train with the biggest grin. Keep the porch light on.\nYour Ike" },

            new Letter { man = "us_gunner_3", at = 1, place = France, body = "Papá,\nFine here. They gave me the gun on a new tank because I shoot fast and I don't miss much. Five years in the Army and they finally put me where I belong. The crew is young. I keep them sharp like the old sergeants kept me. Don't worry about me, you know I can take care of myself. Tell Mamá I go to Mass when there is a chaplain. How is the railroad? Don't lift the heavy things yourself, let the young ones.\nRay" },
            new Letter { man = "us_gunner_3", at = 3, place = Belgium, body = "Papá,\nBad fighting here. I won't write about it. The boys on my tank did good. Better than good. I was proud of them, and I don't say that easy. It's cold, colder than the mountains in January. I think about the desert after rain, the smell of the creosote. Nobody here knows what that smells like. I'll show them one day. Take care of Mamá. I'm fine.\nYour son, Ray" },
            new Letter { man = "us_gunner_3", at = 5, place = Germany, body = "Papá,\nSix years in the Army this month, longer than anybody in the battalion. When this is over I might stay in, or I might come home and work the railroad with you. I don't know yet. I know I want to sit on the porch with you and not talk. You taught me to do a hard job without making noise about it. That's what I've done here. I hope you're proud. I'll be home.\nRay" },

            new Letter { man = "us_gunner_4", at = 1, place = France, body = "Dear Da,\nThey said a woman couldn't sit a gun in a tank. Then I outshot the lieutenant three times running, and now they say I'm the exception. I'll be the rule soon enough. The crew treats me like a kid sister, which means they tease me and would die for me. I'd do the same. Your police whistle is on my dog tags, for luck. Tell Mam I'm eating, and tell the boys at the station house their Maggie is doing just fine.\nYour girl, Maggie" },
            new Letter { man = "us_gunner_4", at = 3, place = Belgium, body = "Dear Da,\nIt's colder here than Fairmount Park in a February snow. We've had a bad week and I won't lie to you, I've been scared. But scared and steady, the way you said you were the night of the Kensington fire. I think of you walking into that building and I keep my eye on the sight. Say a prayer for the crew at St. Malachy's. They're good lads, all of them.\nMaggie" },
            new Letter { man = "us_gunner_4", at = 5, place = Germany, body = "Dear Da,\nIt'll be over soon. When I come home I'm going to take the police exam, and I'll pass it, and you'll have to call me Officer O'Hara at the dinner table. Don't laugh. I've done harder things this year than any exam. I've learned what I'm made of, and it's you, mostly. Save me a seat at the Phillies game. I'm buying.\nYour Maggie" },

            new Letter { man = "us_loader_1", at = 1, place = France, body = "Querida Lupe,\nThey made me the loader, which means I pass the big shells to Dale all night and he gets the credit. Same as the bakery: I carry, somebody else gets the thank-you. I got your letter and the picture of Rosa. I showed everybody in the platoon. Eddie says she has my ears; I hope she has your everything else. Kiss her twice for me, once for today and once for the day I left. I'm eating fine. Tell your mother the Army coffee is worse than hers.\nTe quiero, Frank" },
            new Letter { man = "us_loader_1", at = 3, place = Belgium, body = "Querida Lupe,\nChristmas in the snow. Rosa must be sitting up by now. I keep her picture in my helmet so she's the first thing I see and the last. We lost a tank from the platoon this week. The men got out, thank God, but it made us all quiet. I say a Hail Mary before every night and one after, and so far both get answered. Buy her something red from me. I owe you a dance at the Palladium, and I always pay.\nTu Frank" },
            new Letter { man = "us_loader_1", at = 5, place = Germany, body = "Querida Lupe,\nSpring here too. The fields are green, the trees are white, and for a whole day nobody shot at us. I sat on the tank and ate a German apple and thought about our street. When I come home I'm going to learn how to be a father to a girl who doesn't know my face yet. Show her the picture every night and tell her that's papi. I'll take the early shift at the bakery for the rest of my life and never complain once.\nTu Frank, siempre" },

            new Letter { man = "us_loader_2", at = 1, place = France, body = "Dear Betty,\nHello from France! I'm a loader on a Sherman, and I can stow more rounds in this tank than anybody. They say I pack it like my mother packs a lunch pail. It's the steel mill in me. How is the plant? I bet you're the fastest riveter on the line. I told the fellows my girl builds bombers and they didn't believe me, so send a picture of you in your coveralls. And how are the Pirates doing? Our driver is a Cubs fan, so you can imagine.\nYour Billy" },
            new Letter { man = "us_loader_2", at = 3, place = Belgium, body = "Dear Betty,\nI turned nineteen in a foxhole under our tank. The fellows gave me a Hershey bar with a match stuck in it. I'm not a kid anymore, Betty. I've seen things. But I still think about the dance at the Syria Mosque and you in the blue dress, and that helps more than anything. When I get back I'm going to get on at the mill and save up and we'll get a place with a porch. I haven't asked yet. I'm asking now. Kind of.\nBilly" },
            new Letter { man = "us_loader_2", at = 5, place = Germany, body = "Dear Betty,\nWell, I guess you said yes, because your letter had eleven x's on it and the word YES in capitals. The whole crew cheered. Frank cried a little, but he says it was the smoke. We're almost done here. The German towns are full of white sheets hanging out of the windows. I'll be home for good, and I'll carry you over the doorstep of whatever place we can afford. Tell your mother I'll be respectful. Mostly.\nYour fiancé (!), Billy" },

            new Letter { man = "us_loader_3", at = 1, place = France, body = "Cara Mamma,\nDon't worry. I eat, I sleep, I go to Mass when there's a priest, and I wear the sweater. They made me loader. I handle the explosive shells, the big ones, and the sergeant says I have a feel for them. I told him I learned it carrying Papa's fish crates at four in the morning; nothing is heavier. Tell Sal, when you write to his ship, that the Army is winning the war while the Navy takes a cruise. Kiss Papa. Light a candle for the whole crew.\nTuo figlio, Lou" },
            new Letter { man = "us_loader_3", at = 3, place = Belgium, body = "Cara Mamma,\nBuon Natale. We had Christmas dinner out of a can, but Frank found a chicken somewhere, I don't ask, and I cooked it with an onion and the salt I was saving. The whole crew said it was the best meal of the war. I told them to wait until they taste your gravy. They're all invited to Sunday dinner after, I promised, so make extra. Things have been hard here. I'm all right. Your rosary is in my pocket every night.\nLou" },
            new Letter { man = "us_loader_3", at = 5, place = Germany, body = "Cara Mamma,\nI heard from Sal. He's all right, thank God. Two sons, two oceans, and both coming home. It's almost finished here. I've seen too many broken towns, Mamma, and too many mothers like you standing in the doorways. When I come home I'm going to work the store with Papa and never complain about the smell of fish again. Set the table for two more in the summer. Make the lasagna.\nTuo Lou" },

            new Letter { man = "us_loader_4", at = 1, place = France, body = "Dear Ma,\nRemember when I filled shells at the plant and said someday I'd like to see where they go? Well. Now I load them. They're heavier than they look, but I'm stronger than I look, so it works out. The men didn't want me at first. Then I loaded faster than anybody in the company, and now they fight over who gets me. Don't cry. I'm careful. Give Pa my love and make him eat his vegetables.\nYour Rosie" },
            new Letter { man = "us_loader_4", at = 3, place = Belgium, body = "Dear Ma,\nWigilia in the snow. I broke a cracker with the crew like it was opłatek and told them about the Christmas Eve supper, the twelve dishes and the empty chair for the stranger. They were quiet a long time after. Then Frank said, save me the chair. I'm keeping a list of everybody I've promised pierogi to. It's long. Better start rolling the dough now.\nKocham cię, Rosie" },
            new Letter { man = "us_loader_4", at = 5, place = Germany, body = "Dear Ma,\nThe war is almost done, and I've carried more shells than I ever filled at the plant. My arms look like Pa's. When I get home I want my old job back, or maybe a better one. I've learned I can do anything a man can do in a tank, and I'm not going back to being told otherwise. You raised me like that, so it's your fault. Make pączki for Easter next year. I'll be there.\nYour Rosie" },

            new Letter { man = "us_driver_1", at = 1, place = France, body = "Hey Stash,\nGuess who drives a tank. Thirty-three tons, and she goes where I point her, mostly. Sarge says I have a lead foot. I told him that's the Kowalczyk foot, ask the cops on Ashland Avenue. Don't tell Ma that part. You're the man of the house now, so mind her, take out the ashes, and don't fight the Mahoney kids unless they start it. How are the Cubs doing? Write me the scores.\nYour brother, Eddie" },
            new Letter { man = "us_driver_1", at = 3, place = Belgium, body = "Stash,\nCold enough here to freeze the grease in the tracks. We had a rough night last week and I drove us out of it backwards, through a fence and a barn, with Frank yelling Spanish prayers the whole way. Don't tell Ma that either. You'd like Sam, our radio man. He built a radio out of a cigar box once. When I get home I'll teach you to drive the truck, but only if your grades are good. I mean it. Somebody in this family has to finish school.\nEddie" },
            new Letter { man = "us_driver_1", at = 5, place = Germany, body = "Stash,\nI got your report card. A B in arithmetic! Ma wrote that you did it yourself. I showed the whole crew and Dale said you must take after him. We're deep in Germany now. It's almost over, kid, I can feel it. When I get home we're going to Wrigley on opening day, you and me, bleacher seats, hot dogs, the works. I'll drive. Slow, I promise. Take care of Ma till then.\nYour big brother, Eddie" },

            new Letter { man = "us_driver_2", at = 1, place = France, body = "Dear Helen,\nYour husband is a tank driver and, more to the point, the fellow everybody comes to when something rattles. This Sherman has a radial engine like an airplane, and I talk to it like I used to talk to the old Model A. It listens better than the kids do. The boys call me Pop because I'm thirty. The Ford plant trained me better than the Army did; tell the foreman that. Kiss Mary and little Joe. Don't let Joe near my tools.\nYour Andy" },
            new Letter { man = "us_driver_2", at = 3, place = Belgium, body = "Dear Helen,\nCold snap. I've been sleeping with the engine, you'd laugh. If she won't start at four in the morning, the whole crew is in trouble, so I baby her like our first car. Last week I fixed a track in the snow, with Frank holding the wrench and swearing in two languages. Don't worry. I know what I'm doing. Tell Joe his daddy says do his homework and help you with the coal. I think about you in the kitchen every night.\nAndy" },
            new Letter { man = "us_driver_2", at = 5, place = Germany, body = "Dear Helen,\nWe've driven this old girl from the beaches to Germany, and she's never once left us stranded. I'm prouder of that than of anything. When I come home I'm going back to the plant, and on weekends I'm going to build Joe a soapbox racer, teach Mary to drive when she's old enough, grow tomatoes, and never again sleep outdoors. Save me the good chair. I'm coming home to it.\nYour Andy" },

            new Letter { man = "us_driver_3", at = 1, place = France, body = "Chère Mémère,\nThey speak French here, can you believe it, but a funny French, not like ours. The farmers laugh at mine and give me cider anyway. I drive the tank across their fields and over their ditches, and the fellows say I drive like there's no such thing as a bump. I told them to try a pirogue in the Atchafalaya when a gator swims under it. Pray for us. Tell Pépère I still have his rosary, and his fiddle tunes in my head.\nTon Hank" },
            new Letter { man = "us_driver_3", at = 3, place = Belgium, body = "Chère Mémère,\nSnow on the ground, like the one time you told me about when you were a girl. The roads here are ice and mud and forest, and I've taken the tank down places a goat wouldn't go. The crew holds on and says a few words to God. I miss your gumbo and the smell of the kitchen on Sunday. Some nights I hum the old songs over the engine so the boys can sleep. They say it helps. Hug everybody.\nHank" },
            new Letter { man = "us_driver_3", at = 5, place = Germany, body = "Chère Mémère,\nThe war's nearly done. I met a German farmer yesterday who had lost two sons, and he gave us bread anyway. I think about that a lot. When I get home I want to sit on your gallery and watch the cane grow and play Pépère's fiddle badly while you tell me to stop. That's all. Keep the coffee strong.\nTon petit-fils, Hank" },

            new Letter { man = "us_driver_4", at = 1, place = France, body = "Querida Carmen,\nYour big sister drives a tank! Remember when Papá said I drove his truck like a crazy lady? Well, now I have thirty tons to be crazy with. Don't tell him. The roads here are narrow with hedges on both sides, and I squeeze the tank through like threading a needle. Study hard, help Mamá, and don't let Tony Salazar walk you home. I'll know. I always know.\nTu hermana, Dolly" },
            new Letter { man = "us_driver_4", at = 3, place = Belgium, body = "Querida Carmen,\nIt snows so much here you'd think El Paso was a dream. The crew calls me the smoothest driver in the battalion, and last week I got us out of a bad place so fast the gunner lost his helmet. I laughed about it later. Not then. I miss the mountains at sunset and Mamá's tamales at Christmas. Eat two for me. Write to me about school. I want to hear everything, even the boring parts.\nDolly" },
            new Letter { man = "us_driver_4", at = 5, place = Germany, body = "Querida Carmen,\nIt's almost over. When I come home I'm going to teach you to drive, the real way, on the desert road where Papá can't see us. Then I'm going to find a job driving something, a bus, a truck, anything with an engine, and nobody is going to tell me girls can't. You'll see. The world is going to be different after this. Make sure you're ready for it.\nTu hermana que te quiere, Dolly" },

            new Letter { man = "us_radio_1", at = 1, place = France, body = "Dear Elena,\nI'm the radio man and the bow gunner, which means I talk to the other tanks and keep my head down. The set is a good one, better than the one I built in your father's garage, remember, when we picked up a ship off Galveston. At night I listen to the static between orders and think about the porch on Guadalupe Street and the crickets. I'm not good at letters. I'm better at radios. But I think about you all the time, and I wanted that written down somewhere.\nYours, Sam" },
            new Letter { man = "us_radio_1", at = 3, place = Belgium, body = "Dear Elena,\nSnow up to the knees, and pine woods like a Christmas card, if Christmas cards had tanks in them. Some nights the radio is the only thing that holds the platoon together. I call the turns and the fellows answer, and it's like we're one animal. I got your letter with the pressed flower. It's flat in my paybook. I've been working up the nerve to ask you something, but not in a letter. In person, with your father's permission and a ring. So wait for me, please.\nSam" },
            new Letter { man = "us_radio_1", at = 5, place = Germany, body = "Dear Elena,\nThe Germans are giving up by the hundreds now. Yesterday a whole company walked up to our tank with their hands up, and I had to radio for somebody to take them, because what do you do with two hundred men and one Sherman? It's almost over. I've been saving my pay. I priced a ring in a shop in Paris when we passed through. It's small, but it's real. I'm going to ask you on the porch, in Spanish, the way your mother likes. Say yes.\nYour Sam" },

            new Letter { man = "us_radio_2", at = 1, place = France, body = "Dear Grandmother,\nI am the radio man on a tank. My job is to listen and to pass on what I hear, which you always said I was good at. France is green everywhere, with small fields and old stone walls. The rain comes every day. I think of the red mesa and the sky at home, how you could see a storm coming for an hour. Here nothing can be seen coming. I pray in the morning, facing east, as you taught me. I am well.\nYour grandson, Tom" },
            new Letter { man = "us_radio_2", at = 3, place = Belgium, body = "Dear Grandmother,\nThe snow here is deep and the forest is dark even in the day. On clear nights the stars are the same ones, and I find the ones you named for me when I was small. That helps. My crew trusts my voice on the radio. When the night is bad I speak slowly and calm, and they say it makes them calm. I think that is from you. Please tell my uncles I am doing a man's work. I will come home.\nTom" },
            new Letter { man = "us_radio_2", at = 5, place = Germany, body = "Dear Grandmother,\nSpring has come here too, and the fighting is almost over. I have seen the land burned in many places, and I want to come home and see land that is whole. I want to sit with you outside when the sun goes down and not speak. I have a stone from each country we crossed, for you. I will bring them to the house.\nYour grandson, Tom" },

            new Letter { man = "us_radio_3", at = 1, place = France, body = "Dear Kathleen,\nTen years writing up fires and ballgames for the paper, and it turns out the Army wanted a man who notices things. I'm the radio operator and spotter, which means I see the trouble first and say so, calmly, over the net. The country here is beautiful in a way that makes the war seem rude: stone churches, apple trees, cows who ignore us. I'm keeping notes for a book, or at least for the boys at the paper. Kiss the children.\nYour Al" },
            new Letter { man = "us_radio_3", at = 3, place = Belgium, body = "Dear Kathleen,\nI've stopped keeping notes. There are things I don't want to write down and things I couldn't if I tried. The boys in my tank are the finest people I've known, and most of them aren't old enough to vote. I spot for them. It's the most important job I've ever had, and I've covered the mayor. Don't worry about me; I'm the careful sort. I miss your voice more than your cooking, and that is saying a great deal.\nAl" },
            new Letter { man = "us_radio_3", at = 5, place = Germany, body = "Dear Kathleen,\nI've started writing again. Not the war. The men: Dale's steady hands, Frank's pictures of the baby, the way Eddie backs a tank through a barn. Someone should remember them properly. The end is close. When I get home I want a quiet Sunday, the paper, the kids fighting over the funnies, and you telling me to put the pen down. I will, for a while. Not forever.\nYours always, Al" },

            new Letter { man = "us_radio_4", at = 1, place = France, body = "Dearest David,\nTwo years at the switchboard in Atlanta, and it turns out I can connect tanks as well as telephone calls. I'm the radio operator, and when the platoon talks, it talks through me. Isn't it strange, both of us in the war, you over one ocean and I over the other? I look at the moon and think it's looking at you too, somewhere over the Pacific. Fly carefully. I keep your letters in a tobacco tin, all forty-one of them.\nAll my love, Grace" },
            new Letter { man = "us_radio_4", at = 3, place = Belgium, body = "Dearest David,\nYour letter came six weeks late, and I read it nine times. I'm glad you have a good crew chief. So do I, in a way: my crew keeps me warm and fed and laughing when there's no reason to. It's snowing. Some nights the radio goes quiet and I hear my heart in the earphones. Then someone calls in, and I answer, and it steadies. Promise me the wedding will be in June, in Mama's garden.\nGrace" },
            new Letter { man = "us_radio_4", at = 5, place = Germany, body = "Dearest David,\nThe war here will be over any day, and I hear yours is turning too. I've decided things. We'll marry in June, in Mama's garden, and you'll wear your wings and I'll wear my stripes under the dress, just for us. Then we'll go somewhere quiet, where no radio ever crackles. Come home to me, darling. I'm nearly done with being brave.\nYours, Grace" },

            // ---- the Soviets ----
            new Letter { man = "su_gunner_1", at = 1, place = Kursk, body = "Dear Mama,\nGreetings from the front. I am alive and well, which is the main thing. They made me gunner on a T-34, because I shoot straight, like at the hares with Papa. The steppe here is wide and hot, not like our meadows on the Oka. The crew is good: the loader is from Leningrad and the driver from the Kuban, and they argue about whose bread is better. Tell Nyura and Olya to help you with the hay. Is there any news from Papa? Write to me.\nYour son Vasya" },
            new Letter { man = "su_gunner_1", at = 3, place = Belorussia, body = "Dear Mama,\nWe go forward every day now. The villages here are burned, only the chimneys stand, and the people come out of the forest thin as sticks and give us what they have. I give them my sugar. I have been at the front a whole year. Mama, don't cry when you read this, but I feel older than Papa. When I come home I'll fix the roof, and we'll all go fishing on the Oka.\nYour Vasya" },
            new Letter { man = "su_gunner_1", at = 5, place = Reich, body = "Dear Mama,\nWe are in Germany. The end is near, everyone says so, and I believe it. I dream of home every night now: the Oka in the morning, the mist, the bells from across the river. I carry your little icon in my tunic, next to my Komsomol card, and they don't argue. Soon I'll be home, Mama. Put the samovar on and don't take it off.\nYour son Vasya" },

            new Letter { man = "su_gunner_2", at = 1, place = Kursk, body = "Dasha, my dear,\nI am alive and well. They put me at the gunsight, because a Siberian hunter sees a sable in the snow at three hundred paces, and a German tank is bigger than a sable. The steppe here is flat as a table, and hot. I miss the taiga and our cabin and the smell of the stove. Kiss our Lyuba for me. Tell her Papa will bring her a present from the front. I don't know what yet.\nYour Tolya" },
            new Letter { man = "su_gunner_2", at = 3, place = Belorussia, body = "Dasha, my dear,\nForests and swamps here, almost like home, only the birds are different. The crew says I see the enemy before he sees himself. It's my eyes that keep them alive, and I carry that like a heavy pack. I don't sleep much. When I do, I dream of us on the Angara in summer, you in the boat, laughing. Lyuba is four now. Does she remember me? Show her my picture.\nTolya" },
            new Letter { man = "su_gunner_2", at = 5, place = Reich, body = "Dasha, my dear,\nThe war is almost finished. I have seen too much, Dasha. When I come home I want to hunt only for our table and never for anything else. I want to chop wood and sit by the stove and listen to Lyuba read. Wait for me. I'll come on the Trans-Siberian, and it will be the longest journey of my life, and the best.\nYour Tolya" },

            new Letter { man = "su_gunner_3", at = 1, place = Kursk, body = "Dear Father,\nYou will be pleased: I am applying mathematics. A gunner's work is trigonometry and nerve, and I have more of the first than the second, so far. The crew calls me the Professor, which I hope you find as funny as I do. We are in the steppe, in the south. It is loud. Please send me a chess problem in your next letter; the loader plays, badly, and I need a real opponent.\nYour son Pavel" },
            new Letter { man = "su_gunner_3", at = 3, place = Belorussia, body = "Dear Father,\nYour chess problem took me four days. Mate in three, very elegant. I solved it under the tank in a rainstorm. I have changed, Father. The war is not a problem to be solved; it is only to be endured, and I have endured it for a year. But the crew is my family, and I am fast with the gun because they need me to be. When I come back I will finish my studies. That is a promise.\nPavel" },
            new Letter { man = "su_gunner_3", at = 5, place = Reich, body = "Dear Father,\nIt is nearly over. I have calculated it: two thousand kilometres from Kursk to here, on a tank. When I come home I want to sit in your study with the lamp and the books and play chess until morning, and not talk about any of this. Then, in September, the university. Mathematics is quiet. I have learned to love quiet.\nYour son Pavel" },

            new Letter { man = "su_gunner_4", at = 1, place = Kursk, body = "Dear Mama,\nI am alive and well and at the gun. Sniper school taught me patience, and a tank gun is only a bigger rifle. The men were suspicious of me for a week. Now they don't go into battle without me. I carry Papa's photograph in my pocket. I think of him in '41, and I aim. Don't worry about me, Mama. Worry about eating. Smolensk will be free soon, I promise.\nYour Anya" },
            new Letter { man = "su_gunner_4", at = 3, place = Belorussia, body = "Dear Mama,\nYour letter came from Smolensk, free Smolensk! The house is standing and you are well. I read it in the tank, and the whole crew made me read it again, aloud. I'm a sergeant now. The crew says my gun keeps them alive. I don't feel like a hero. I feel like Papa's daughter, doing what he couldn't finish. We go west. I'll be home when it's done.\nAnya" },
            new Letter { man = "su_gunner_4", at = 5, place = Reich, body = "Dear Mama,\nWe are in Germany, and I have finished Papa's work. I felt nothing when we crossed the border, only tiredness, and then I cried for him for the first time since '41. The crew held me. When I come home I want to plant a garden where the old one was, apple trees for Papa. And I want to teach little children, and teach them nothing about guns.\nYour Anya" },

            new Letter { man = "su_loader_1", at = 1, place = Kursk, body = "Tanya, my own,\nI am alive and well. I load the gun, and the shells are heavy, but not as heavy as that first winter in Leningrad, you know. Every time we get a new tank from the rear, I look at the factory stamp to see if it is from Chelyabinsk. If it is, I think your hands touched it. So I fight in a tank you built, maybe. Write to me about the factory, and whether you are eating. Eat, Tanya. Please.\nYour Kolya" },
            new Letter { man = "su_loader_1", at = 3, place = Belorussia, body = "Tanya, my own,\nLeningrad is free! We heard it on the radio in January and the whole crew shouted. I cried, and I'm not ashamed. Now we go west, fast. Our tank was hit last month; we got out, and the new one came from Tankograd. I found the stamp. I kissed it. The boys laughed, but they understood. Soon, Tanya, we'll both go home to the Neva, and walk along the embankment, and I'll never let go of your hand.\nKolya" },
            new Letter { man = "su_loader_1", at = 5, place = Reich, body = "Tanya, my own,\nWe are almost at Berlin. I load, and I think of you at the lathe, and it feels like we are working the same shift. When it's over we'll go home to Leningrad. The Kirov works will need us both. We'll get a room, even a small one, with a window onto the Neva, and a table, and bread on the table every day. That's all I want. Bread, you, and the Neva.\nYour Kolya" },

            new Letter { man = "su_loader_2", at = 1, place = Kursk, body = "Dear Mama,\nI'm alive and well. I carry the shells and stow them in the tank, and the sergeant says I fit more in than anyone, like our cellar in autumn. The food is good, bread every day. Is the harvest good this year? Who is working the field without me and Papa? Tell Grandad to rest his back. I dream of the Volga in the evening, the barges, and the singing from the other bank.\nYour son Misha" },
            new Letter { man = "su_loader_2", at = 3, place = Belorussia, body = "Dear Mama,\nIt's a year I've been at the front. I have grown, Mama; the tunic is tight. We freed a village yesterday, and an old woman gave me milk and called me son, and I had to go behind the tank so no one would see my face. She looked like you. Don't worry, I keep my head down. When I come home I'll take Papa's place in the field, and you won't have to work so hard.\nMisha" },
            new Letter { man = "su_loader_2", at = 5, place = Reich, body = "Dear Mama,\nWe are in Germany. Everything here is neat and the houses are stone, but I would give all of it for our house by the Volga. The war is ending. I'll be home for the harvest, if God and the sergeant allow. Bake the round loaf, the big one, with salt on top. I'll eat half of it at the gate.\nYour Misha" },

            new Letter { man = "su_loader_3", at = 1, place = Kursk, body = "Dear Galya,\nGreetings to you and the children. I am alive and well. The young ones in the crew call me Batya, because I'm thirty-five and they are babies. I handle the high-explosive shells. Twenty years in the mine taught me about explosives, and I respect them, which is why I'm still alive. How are Petya, Kostya and little Ninochka? Do they mind you? Is there coal for the winter?\nYour Stepan" },
            new Letter { man = "su_loader_3", at = 3, place = Belorussia, body = "Dear Galya,\nYour letter came: the Donbass is free and the mine is working again! I read it aloud to the crew, and they cheered for my mine as if it were theirs. I think of the children every night. Petya must be as tall as you. Tell him to help you and to study, and not to go down the pit. There will be better work after the war, for all of them.\nStepan" },
            new Letter { man = "su_loader_3", at = 5, place = Reich, body = "Dear Galya,\nIt's nearly over. I've kept my boys alive, all of them, and they've kept me. When I come home I'll go back underground if they need me, but first I'm going to sit in our garden under the cherry tree for a whole week and do nothing at all. Kiss the children. Tell Ninochka her papa is coming, the one with the moustache.\nYour Stepan" },

            new Letter { man = "su_loader_4", at = 1, place = Kursk, body = "Ninochka, hello!\nYour Katya is a tank loader! Can you imagine, me, who used to lift bales of calico at the mill. Shells are heavier, but my arms remember. The boys teased me for a day, then they saw me load and stopped. How are the girls at the mill? Are you still singing at the looms? Sing for me. We sing too, at night, and my voice is the best in the crew, which isn't saying much.\nYour Katya" },
            new Letter { man = "su_loader_4", at = 3, place = Belorussia, body = "Ninochka, hello!\nWe've been in the forests and swamps for a month, and I load, and load, and load, till my hands forget they're mine. I got a medal for courage. I didn't feel brave; I was just angry and fast. Tell the girls at the mill that the calico you weave becomes bandages, and I've seen your bandages save a man. Keep weaving.\nKatya" },
            new Letter { man = "su_loader_4", at = 5, place = Reich, body = "Ninochka, hello!\nThe war is ending! When I come home we'll put on our best dresses and go dancing at the club, and I'll dance until the soles fall off my shoes. Then I'll come back to the mill, or maybe not; maybe I'll learn to drive. After this, a woman can do anything. Keep a place for me at the loom beside yours, just in case.\nYour Katya" },

            new Letter { man = "su_driver_1", at = 1, place = Kursk, body = "Dear Grandad,\nYour grandson drives a T-34! It's just a tractor with a gun and a temper, and I've driven tractors since I was twelve, so no trouble. The crew says I drive like I'm late for a wedding. How is the kolkhoz? Is the wheat good? I miss the Kuban fields, the sunflowers taller than me. Look after Grandma, and don't go climbing on the roof; I'll fix it after the war.\nYour Sasha" },
            new Letter { man = "su_driver_1", at = 3, place = Belorussia, body = "Dear Grandad,\nWe go forward through swamps where I thought no tank could go, but a Kuban tractor driver finds the way. Last week I pulled another tank out of the mud with ours, and the commander gave me a watch. A real one! I'll show you. Grandad, I've seen a lot. I understand now why you never talked about your war. I won't talk about mine either. But I'll come home.\nSasha" },
            new Letter { man = "su_driver_1", at = 5, place = Reich, body = "Dear Grandad,\nThe German roads are straight and smooth, a pleasure to drive, but I'd rather drive the old tractor down our dusty road to the river. The war is almost over. When I come home I'll take the tractor out for the autumn ploughing, and you can ride beside me and tell me I'm doing it wrong, like always.\nYour grandson Sasha" },

            new Letter { man = "su_driver_2", at = 1, place = Kursk, body = "Verochka,\nYour sister is a tank driver-mechanic! The men looked at me like a cat at a wedding, until the engine died on the march and I fixed it in twenty minutes with a hairpin and a wrench. Now they call me Lenochka the Engineer and bring me their broken watches. Three years at the car works weren't wasted. Tell Mama I'm eating and I wear the scarf she knitted.\nYour Lena" },
            new Letter { man = "su_driver_2", at = 3, place = Belorussia, body = "Verochka,\nWe've come a long way, hundreds of kilometres, and our engine hasn't failed once, because I don't let it. The crew trusts me with their lives every time we move. That's a strange thing to carry. I think I've become stricter, like Mama. Are you studying? After the war you will go to the institute, both of us, I've decided. Engineers, Vera. The country will need to be rebuilt.\nLena" },
            new Letter { man = "su_driver_2", at = 5, place = Reich, body = "Verochka,\nI've driven all the way to Germany. Imagine, your sister, who you said couldn't ride a bicycle! The end is close. When I come home I'm going to the institute to become a real engineer, and I'll design a tractor so good nobody will ever need a tank again. Tell Mama to bake the cabbage pie.\nYour Lena" },

            new Letter { man = "su_driver_3", at = 1, place = Kursk, body = "Dear Mother,\nI'm alive and well and fighting near Kursk, not far from home, but I cannot come to you: the Germans are still in our Poltava. I don't know if my letters reach you. I write anyway, and I'll keep writing until you answer. I drive the tank over anything, mud, ditches, fences, and the lads say I drive like our old bull. Soon we'll push them out of Ukraine. Wait for me, Mother.\nYour son Ivan" },
            new Letter { man = "su_driver_3", at = 3, place = Belorussia, body = "Dear Mother,\nYour letter came after two years! You are alive! The house burned, but you are alive, and Hanna and the little ones too. I read it until the paper tore. Mother, I will build the house again with my own hands, bigger than before, with a porch facing the orchard. Now I fight twice as hard, because I know you're waiting. Plant the cherries.\nIvan" },
            new Letter { man = "su_driver_3", at = 5, place = Reich, body = "Dear Mother,\nWe are in Germany, at the end of the road. I have driven two thousand kilometres to get here, and now I only feel tired, and I want to go home. I will build the house, Mother. I will marry, I promise, and you will have grandchildren running in the orchard. Put the cherries on the table in the summer. I am coming.\nYour son Ivan" },

            new Letter { man = "su_driver_4", at = 1, place = Kursk, body = "Petya, my dear,\nI am alive and well, and I drive a tank the way I drove the tractor in our brigade, straight and without fuss. The crew is good. They call me Mother, although I'm only twenty-seven, because I scold them about their socks. Where are you? Your last letter was from the Don. Take care of your hands, sapper. I need them after the war, for the house.\nYour Nadya" },
            new Letter { man = "su_driver_4", at = 3, place = Belorussia, body = "Petya, my dear,\nWe're far west now. The roads are sand and swamp, and I drive by feel. Your letter came: you're alive, you're on the Dnieper. Two fronts, Petya, but the same war and the same sky. I look at the Plough every night and think you're looking too. When the war ends we'll go home to Altai and plough the virgin land, you and I, and plant a whole life.\nNadya" },
            new Letter { man = "su_driver_4", at = 5, place = Reich, body = "Petya, my dear,\nIt's almost over. I've driven from Kursk to Germany without losing a single one of my crew to my driving, and I'm proud of that. When we're home I want children, three at least, and a big house with a stove, and the tractor brigade again, and you with me. Two soldiers in a village. We'll tell the children about the war only once, and then never again.\nYour Nadya" },

            new Letter { man = "su_radio_1", at = 1, place = Kursk, body = "Mashenka,\nI'm alive and well. They made me radio operator, since I'm the only one who knows what a capacitor is. Three years of physics are finally useful. The steppe is loud, and at night the sky is full of stars, more than in Moscow, and the crew asks me their names. I tell them. How is the hospital? You must be exhausted. Take care of yourself, not only of the wounded.\nYour brother Grisha" },
            new Letter { man = "su_radio_1", at = 3, place = Belorussia, body = "Mashenka,\nI copied out that poem everyone carries, the one about waiting, and gave it to our driver for his girl, since he can't write poems. We are all poets and philosophers at night; in the day we are something else. You see the worst of it in your wards, and I see it from the tank. I think we'll both need a long time to be ordinary again. Let's be ordinary together, at Mama's table.\nGrisha" },
            new Letter { man = "su_radio_1", at = 5, place = Reich, body = "Mashenka,\nWe're close to Berlin. When it's over I'll go back to the university, if it will have me, and study the stars properly this time. You'll become a doctor; I've decided for you. Two Volkovs, a doctor and an astronomer. Papa would have laughed. Put a candle for him in the window. I'll be home soon to light the next one.\nYour brother Grisha" },

            new Letter { man = "su_radio_2", at = 1, place = Kursk, body = "Dear Mama,\nDon't worry, please, I'm fine. I'm with a good crew and they look after me, because I'm the youngest. I'm the signaller: I listen to the radio and pass on the orders, like with my set on the roof, remember, when I talked to a boy in Kazan? Now I talk to a whole regiment. Is Boris the cat all right? Hug him. Hug yourself too, from me.\nYour Yura" },
            new Letter { man = "su_radio_2", at = 3, place = Belorussia, body = "Dear Mama,\nI'm nineteen now. The crew made me a cake out of rusks and condensed milk. I'm not the youngest anymore; there's a boy from Tula who's younger, and I look after him the way they looked after me. Mama, I'm not afraid anymore, or I'm afraid and do the job anyway. I think that's the same thing. I'll come home and study radio at the institute. Keep my soldering iron.\nYura" },
            new Letter { man = "su_radio_2", at = 5, place = Reich, body = "Dear Mama,\nWe are in Germany. When the war ends, they say the radio will announce it, and I'll be the first in the regiment to hear it. I'll shout it to everyone. Then I'll come home and climb onto the roof with my old set and call out to the whole world: this is Yura Belyaev, in Gorky, and the war is over. Wait for me.\nYour son Yura" },

            new Letter { man = "su_radio_3", at = 1, place = Kursk, body = "Lida, dear,\nI am alive and well. A geography teacher makes a good spotter; I read the land like a map, where the ravines are, where a tank can hide. The boys are younger than my pupils were, some of them. Pskov is still under the Germans. I know how hard it is for you, not knowing about your parents. We'll get there. I promise you the first letter I write from home.\nYour Arkady" },
            new Letter { man = "su_radio_3", at = 3, place = "Field post · the Baltic · August 1944", body = "Lida, dear,\nPskov is free! I read everything in the newspapers twice. When I have leave I'll go and find your parents' house. We are going forward so fast the maps can't keep up, and I draw my own on the backs of the old ones. When this is over I'll teach geography again, and I'll show the children where their fathers went. On a map, without the rest.\nArkady" },
            new Letter { man = "su_radio_3", at = 5, place = Reich, body = "Lida, dear,\nWe're near Berlin. I've crossed half of Europe on a tank and seen every river I used to draw on the blackboard: the Dnieper, the Vistula, the Oder. They were just blue lines once. When I come home I'll teach it differently. Put the school globe on our table; I want to spin it with you and find a place where nobody has ever fought.\nYour Arkady" },

            new Letter { man = "su_radio_4", at = 1, place = Kursk, body = "Dear Granny,\nI'm alive and well, and I'm the radio operator in a tank! Before the war I connected calls at the Kharkiv exchange, and now I connect a whole platoon. They say my voice is calm, like yours when you told fairy tales. Kharkiv will be free soon, I know it, and I'll come to you with flowers. Bake the poppyseed rolls. I dream of them every night.\nYour Zoya" },
            new Letter { man = "su_radio_4", at = 3, place = Belorussia, body = "Dear Granny,\nKharkiv is free, and you are alive, and I've read your letter so many times the words are fading. I'm in the forests of Belorussia now. At night, when the radio is quiet, I sing your songs softly into the dark, and the crew listens. They say it's like home. I've grown up, Granny. I'm not afraid anymore. Well, only a little, like everyone.\nZoya" },
            new Letter { man = "su_radio_4", at = 5, place = Reich, body = "Dear Granny,\nIt's the last spring of the war. Everyone knows it. When I come home I'll go back to the exchange and connect people's calls, happy calls only: births, weddings, I'm home. And the first call will be to you. Wait for me by the window, where you always wait.\nYour Zoya" },
        };

        static string Key(Letter l) => "letter." + l.man + "." + l.at;
        /// <summary>Written: its writer has served a night in the seat (the first letter), or trained to its level.</summary>
        public static bool Written(Letter l)
        {
            if (l.at <= 1) return PlayerPrefs.GetInt("crew." + l.man + ".served", 0) == 1;
            var m = System.Array.Find(Crew.Men, x => x.id == l.man); return m != null && Crew.Level(m) >= l.at;
        }
        /// <summary>Passed by the censor and sent: kept to be read again.</summary>
        public static bool Passed(Letter l) => PlayerPrefs.GetInt(Key(l), 0) == 1;
        public static void Pass(Letter l) { PlayerPrefs.SetInt(Key(l), 1); PlayerPrefs.Save(); }
        /// <summary>The letters waiting on the commander's desk, oldest first (by level, then as listed).</summary>
        public static List<Letter> Waiting()
        {
            var w = new List<Letter>(); foreach (var l in All) if (Written(l) && !Passed(l)) w.Add(l);
            w.Sort((a, b) => a.at != b.at ? a.at - b.at : System.Array.IndexOf(All, a) - System.Array.IndexOf(All, b));
            return w;
        }
        /// <summary>The ones sent, to be read again.</summary>
        public static List<Letter> Sent(string man = null) { var s = new List<Letter>(); foreach (var l in All) if (Passed(l) && (man == null || l.man == man)) s.Add(l); return s; }
        /// <summary>A night fought: the crew in the seats have served, and write their first letters.</summary>
        public static void Served(string nation)
        {
            foreach (var role in Crew.Roles) { var m = Crew.Chosen(nation, role); if (m != null) PlayerPrefs.SetInt("crew." + m.id + ".served", 1); }
            PlayerPrefs.Save();
        }
        public static string Writer(Letter l) { var m = System.Array.Find(Crew.Men, x => x.id == l.man); return m != null ? m.name : l.man; }
    }
}
